### ISSUE TITLE
Exception loading plugin on Paper 1.21

### ISSUE THREAD

**Issue by opl-** [OneLiteFeatherNET/BetterGoPaint#28]
### Server Implementation

Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Server Version

1.21

### Describe the bug

```
[14:15:39 INFO]: This server is running Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
[14:15:51 INFO]: [BetterGoPaint] Enabling BetterGoPaint v1.1.0-SNAPSHOT
[14:15:51 INFO]: [BetterGoPaint] Made with ♥ in Germany
[14:15:51 ERROR]: Error occurred while enabling BetterGoPaint v1.1.0-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/org.incendo.cloud.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.lambda$new$0(MinecraftArgumentTypes.java:85) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181) ~[guava-32.1.2-jre.jar:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/org.incendo.cloud.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.getClassByKey(MinecraftArgumentTypes.java:98) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/org.incendo.cloud.bukkit.internal.MinecraftArgumentTypes.getClassByKey(MinecraftArgumentTypes.java:70) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/org.incendo.cloud.bukkit.internal.BukkitBrigadierMapper.registerUUID(BukkitBrigadierMapper.java:132) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/org.incendo.cloud.bukkit.internal.BukkitBrigadierMapper.registerBuiltInMappings(BukkitBrigadierMapper.java:82) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/org.incendo.cloud.paper.ModernPaperBrigadier.<init>(ModernPaperBrigadier.java:118) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/org.incendo.cloud.paper.LegacyPaperCommandManager.registerBrigadier(LegacyPaperCommandManager.java:174) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/org.incendo.cloud.paper.LegacyPaperCommandManager.registerBrigadier(LegacyPaperCommandManager.java:141) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/net.onelitefeather.bettergopaint.BetterGoPaint.enableCommandSystem(BetterGoPaint.java:138) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/net.onelitefeather.bettergopaint.BetterGoPaint.registerCommands(BetterGoPaint.java:113) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/net.onelitefeather.bettergopaint.BetterGoPaint.onEnable(BetterGoPaint.java:97) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-109-5a5035b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-109-5a5035b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.resources.ResourceLocation.<init>(java.lang.String)
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/org.incendo.cloud.bukkit.internal.CraftBukkitReflection.needConstructor(CraftBukkitReflection.java:202) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/org.incendo.cloud.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:54) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        ... 24 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.resources.ResourceLocation.<init>(java.lang.String)
        at java.base/java.lang.Class.getConstructor0(Class.java:3761) ~[?:?]
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930) ~[?:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/org.incendo.cloud.bukkit.internal.CraftBukkitReflection.needConstructor(CraftBukkitReflection.java:200) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        at BetterGoPaint-1.1.0-SNAPSHOT+22.jar/org.incendo.cloud.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:54) ~[BetterGoPaint-1.1.0-SNAPSHOT+22.jar:?]
        ... 24 more
[14:15:51 INFO]: [BetterGoPaint] Disabling BetterGoPaint v1.1.0-SNAPSHOT
```

### To Reproduce

1. Load plugin on Paper 1.21

### Expected behaviour

Plugin works.

### Fawe Debugpaste (if applicable)

https://athion.net/ISPaster/paste/view/6b1c9c65e6ae41cf88cc6dfd3bf55412

### goPaint Version

[1.1.0-SNAPSHOT+22 (Modrinth)](https://modrinth.com/plugin/bettergopaint/version/1.1.0-SNAPSHOT+22)

### Checklist

- [X] I am using the newest build from https://github.com/TheMeinerLP/BetterGoPaint and the issue still persists.

**Comment by TheMeinerLP** [comment]
Please provide the full version of the paper and debug paste of fawe or the issue will be closed as invalid

**Comment by opl-** [comment]
Added the FAWE debug paste and copy-pasted the Paper version from the log below to be more clearly visible.

**Comment by TheMeinerLP** [comment]
Test this version version: https://hangar.papermc.io/OneLiteFeather/BetterGoPaint/versions/1.1.0-SNAPSHOT+29

**Comment by opl-** [comment]
Loads correctly now. Thank you!
