### ISSUE TITLE
Interacting with the inventory throws IncompatibleClassChangeError

### ISSUE THREAD

**Issue by opl-** [OneLiteFeatherNET/BetterGoPaint#29]
### Server Implementation

Paper

### Server Version

Paper 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) for Minecraft 1.21

### Describe the bug

```
[08:10:07 ERROR]: Could not pass event InventoryCreativeEvent to BetterGoPaint v1.1.0
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at BetterGoPaint-1.1.0-SNAPSHOT+29.jar/net.onelitefeather.bettergopaint.listeners.InventoryListener.menuClick(InventoryListener.java:59) ~[BetterGoPaint-1.1.0-SNAPSHOT+29.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor26.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-109-5a5035b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-109-5a5035b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCreativeModeSlot(ServerGamePacketListenerImpl.java:3333) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:30) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:20) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-109-5a5035b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### To Reproduce

1. Open the GUI by left-clicking a feather
2. Click any item
3. Nothing happens and item gets picked up

### Expected behaviour

1. Relevant action is performed instead 

### Fawe Debugpaste (if applicable)

https://athion.net/ISPaster/paste/view/41fc9f4c20c8499ea760025e5e6b5fe1

### goPaint Version

BetterGoPaint-1.1.0-SNAPSHOT+29 (Modrinth)

### Checklist

- [X] I am using the newest build from https://github.com/TheMeinerLP/BetterGoPaint and the issue still persists.

**Comment by TheMeinerLP** [comment]
![Screenshot_20240728_151831](https://github.com/user-attachments/assets/9cb8e039-8eb9-444b-8138-471ccfbb4e16)
Confirmed need more time
